---
services:
  app:
    image: ghcr.io/skrtheg/walmart_sales_forecasting:latest
    container_name: walmart_sales_forecasting
    ports:
      - "7000:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: walmart_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --stop-timeout 60s 