name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: walmart_sales_forecasting
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{env.REGISTRY}}/skrtheg/${{env.IMAGE_NAME}}:latest
     
      - name: Log out from Docker Hub
        run: docker logout